name: Run checks before merge

on:
  pull_request:
  # paths:
  #   - "**/*.js"
  #   - "**/*.json"
  #   - "**/*.ts"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml
