name: Run checks before merge

on:
  pull_request:
    paths:
      - "**.js"
      - "**.mjs"
      - "**.json"
      - "**.ts"
    paths-ignore:
      - "dist/*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml
